# Étape 1 : Base
FROM node:20.12.1-alpine3.18 AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN npm install -g pm2

# Étape 2 : Installation des dépendances
FROM base AS deps
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
RUN yarn install --frozen-lockfile

FROM deps AS production
COPY . .
RUN chmod +x ./src/scripts/setup.sh
EXPOSE 9000

CMD ["./src/scripts/setup.sh"]